spring:
  profiles:
    active: prod
  mvc:
    dispatch-options-request: true
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: ${DB_URL}/in_box
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
  mail:
    host: ${SMTP_HOST}
    port: 587
    username: ${USER_EMAIL}
    password: ${USER_PASSWORD}
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
logging:
  config: classpath:logback-spring-${spring.profiles.active}.xml
  level:
    root: info